application: movie-db-api
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.htm
  upload: index.htm

- url: /find
  script: find.app

- url: /title/tt\d+
  script: title.app

- url: /tests
  script: tests.app
  login: admin
  secure: always

builtins:
- appstats: on
- remote_api: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.sh$
