#!/bin/bash
# Package upgrade all Debian VEs using vzexec.

update_all() {
  local veid
  for veid in $(vzlist -Ho ctid); do
    if ! grep -q Debian /var/lib/vz/private/$veid/etc/issue.net; then
      continue
    fi
    echo "--- Updating VE $veid"
    ve_update $veid || return 1
    echo
  done
}

ve_update() {
  ve_exec $1 'apt-get update' && \
    ve_exec $1 'aptitude upgrade' && \
    ve_exec $1 'aptitude clean'
}

ve_exec() {
  if ! vzctl exec $1 "$2"; then
    echo "Error: '$2' failed"
    return 1
  fi
}

main() {
  update_all
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
  main "$@"
fi
